config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations', sessions: 'users/sessions' }
    
  resources :users do
    resources :posts, only: [:index, :show]
  end

  resources :users do  
    resources :categories do
      resources :products do
        resources :posts, only: [:index, :show]
      end
    end
  end

  post '/posts/:id/buy', to: "posts#buy", as: "buy"
  

  resources :wishlists do
      resources :votes, only: [:create]
  end

  get 'admin' => 'home#admin', as: 'admin'

  scope '/admin' do  
    resources :categories do
      resources :products do
        resources :posts
      end
    end
  end

  scope '/', controller: :main do
    get 'categories' #shows all categories
    get 'deals' #shows all deals
    get '/categories/:name', to: 'main#category'
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, dependent: :destroy
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :posts

  has_many :wishlists
  has_many :users, :through => :wishlists 

  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  # validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment :avatar, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :set_category, only: [:update, :destroy, :show, :edit]

  def index
    @categories = Category.all
  end

  def new
  	@categories = Category.new
  end

  def create
  	@categories = Category.new(category_params)
  	if @categories.save
  		redirect_to categories_path
  	else
      render :new
  	end
  end

  def edit
  end

  def show
  end

  def update
    @categories.update(category_params)
    if @categories.save
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @categories.destroy
    redirect_to admin_path
  end


private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @categories = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
      # if want to create post, it need :user_id, :place_name, :place_type, :address, 
        # :bedroom, :bath, :amenity, :cost_per_night,:description   validation
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :set_product, only: [:update, :destroy, :show, :edit]

  def new
  	# @products = Product.new
    @categories = Category.find(params[:category_id])
    @products = @categories.products.build
  end

  def create
  	# @products = Product.new(product_params)
  	# if @products.save
  	# 	redirect_to category_products_path
  	# else
  	# 	render :new
  	# end
    @categories = Category.find(params[:category_id])
    @products = @categories.products.build(product_params)
    if @products.save
      redirect_to category_products_path
    else
      render :new
    end
  end


  def index
    @products = Product.all
  end

  def show
  end

  def edit
  end

  def update
  	@products.update(product_params)
  	if @products.save
  		redirect_to category_products_path
    else
      render :edit
  	end
  end

  def destroy
  	@products.destroy
  	redirect_to admin_path
  end

  private
  def set_product
    @products = Product.find(params[:id])
  end

  def product_params
  	params.require(:product).permit(:category_id, :name, :description,:avatar)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/products/_form.html.erb
<%= form_for [:category, @products] do |f| %>
	<%= f.text_field :name, placeholder: 'Name' %><br> 
	<%= f.text_field :description, placeholder: 'Description' %><br>
	<%= f.submit 'Add Product' %>
<% end %>

app/views/categories/products/edit.html.erb
<h1> Update your product. </h1>
<%= form_for @products, url: category_product_path do |f| %>
	<%= f.text_field :name, placeholder: 'Name' %><br> 
	<%= f.text_field :description, placeholder: 'Description' %><br>
	<%= f.submit 'Update Product' %>
<% end %>

app/views/categories/products/index.html.erb
<a href="/admin">Admin Page</a><br>
<% @products.each do |x| %>
	<%= link_to "#{x.name}", category_product_path(x.category_id, x.id) %><br>
	<%= x.description %><br><br>
<% end %>

app/views/categories/products/new.html.erb
<%= render partial: '/products/form' %>

app/views/categories/products/show.html.erb
<a href="/admin">Admin Page</a><br>

<%= @products.name %><br>
<%= @products.description %><br>
<%= button_to "Edit Product", edit_category_product_path, :method => :get %>
<%= button_to "Delete", category_product_path(:category, @products), :method => :delete %>

<%= button_to "Create a Post", new_category_product_post_path(:category, @products), :method => :get %>