config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations', sessions: 'users/sessions' }
    
  resources :users do
    resources :posts, only: [:index, :show]
  end

  resources :users do  
    resources :categories do
      resources :products do
        resources :posts, only: [:index, :show]
      end
    end
  end

  post '/posts/:id/buy', to: "posts#buy", as: "buy"
  

  resources :wishlists do
      resources :votes, only: [:create]
  end

  get 'admin' => 'home#admin', as: 'admin'

  scope '/admin' do  
    resources :categories do
      resources :products do
        resources :posts
      end
    end
  end

  scope '/', controller: :main do
    get 'categories' #shows all categories
    get 'deals' #shows all deals
    get '/categories/:name', to: 'main#category'
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :set_category, only: [:update, :destroy, :show, :edit]

  def index
    @categories = Category.all
  end

  def new
  	@categories = Category.new
  end

  def create
  	@categories = Category.new(category_params)
  	if @categories.save
  		redirect_to categories_path
  	else
      render :new
  	end
  end

  def edit
  end

  def show
  end

  def update
    @categories.update(category_params)
    if @categories.save
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @categories.destroy
    redirect_to admin_path
  end


private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @categories = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
      # if want to create post, it need :user_id, :place_name, :place_type, :address, 
        # :bedroom, :bath, :amenity, :cost_per_night,:description   validation
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<%= form_for @categories do |f| %>
	<%= f.text_field :name, placeholder: 'Name' %><br> 
	<%= f.submit 'Edit Category' %>
<% end %>

app/views/categories/index.html.erb
<a href="/admin">Admin Page</a><br>
<a href="javascript:history.back()">Go Back</a><br><br>

<% @categories.each do |x| %>
	<%= link_to "#{x.name}", category_path(x) %><br>
<% end %>

<br>
<%= link_to 'See all products', category_products_path(0) %>
<br>
<%= link_to 'See all posts/deals', category_product_posts_path(0,0) %>
<br>
<%= link_to 'Add a Category', new_category_path %>

app/views/categories/new.html.erb
<a href="/admin">Admin Page</a><br>

hello, create a new category here.

<%= form_for @categories do |f| %>
	<%= f.text_field :name, placeholder: 'Name' %><br> 
	<%= f.submit 'Add Category' %>
<% end %>

app/views/categories/show.html.erb
<a href="/admin">Admin Page</a><br>
<%= @categories.name %><br>
<% @categories.products.all.each do |x| %>
	<%= link_to "#{x.name}", category_product_path(x.category_id, x.id) %><br>
	<%= x.description %><br>
	<%= image_tag (x.avatars[0]) %><br><br>
<% end %>

<br><br>
<%= button_to "Edit", edit_category_path, :method => :get %>
<%= button_to "Delete", @categories, :method => :delete %>

<%= link_to 'See all products', category_products_path(@categories.id) %>
<br><%= link_to 'Add a Product', new_category_product_path(@categories) %>