config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations', sessions: 'users/sessions' }
    
  resources :users do
    resources :posts, only: [:index, :show]
  end

  resources :users do  
    resources :categories do
      resources :products do
        resources :posts, only: [:index, :show]
      end
    end
  end

  post '/posts/:id/buy', to: "posts#buy", as: "buy"
  

  resources :wishlists do
      resources :votes, only: [:create]
  end

  get 'admin' => 'home#admin', as: 'admin'

  scope '/admin' do  
    resources :categories do
      resources :products do
        resources :posts
      end
    end
  end

  scope '/', controller: :main do
    get 'categories' #shows all categories
    get 'deals' #shows all deals
    get '/categories/:name', to: 'main#category'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sportify</title>
          <!-- Latest compiled and minified CSS -->
          <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

          <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

          <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>


      <!-- Latest compiled JavaScript -->
          <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

          <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
          <%= csrf_meta_tags %>

            <meta charset="utf-8">
              <meta http-equiv="X-UA-Compatible" content="IE=edge">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <meta name="description" content="">
              <meta name="author" content="">


        </head>




  <body id="page-top" >

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top effect-shadow " style="background-color:white;">
      <div class="container-fluid border-bottom">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
              </button>
              <a class="navbar-brand page-scroll" style="color:gray;" href="/">Sportify</a>
          </div>
          <div>
              <!-- <form class="navbar-form navbar-left" role="search">
                  <div class="form-group">
                      <input type="text" class="form-control" placeholder="Search">
                  </div>
                      <button type="submit" class="btn btn-primary btn-m page-scroll">Submit</button>
              </form> -->
          </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                <%if signed_in? %>
                  <li><a class="page-scroll" style="color:gray; , padding: 0 2em;, line-height: 3em;" > Welcome <%=current_user.email%></li>
                  <li><a class="page-scroll"><%=link_to 'Sign out', destroy_user_session_path, style: 'color:gray;' , method: :delete %></li>
                <% elsif params[:controller] == "home" && params[:action] == "index" %>
                  <li>
                    <a class="page-scroll"><%=link_to "Login" , new_user_session_path %></a>
                  </li>
                  <li>
                    <a class="page-scroll"><%=link_to "Sign up", new_user_registration_path %></a>
                  </li>
                <% elsif params[:controller] == "users/sessions" && params[:action] == "new"%> 
                  <li>
                      <a class="page-scroll"><%=link_to "Sign up", new_user_registration_path %></a>
                  </li>
                <% elsif params[:controller] == "users/registrations" && params[:action] == "new" %> 
                   <li>
                      <a class="page-scroll" ><%=link_to "Login", new_user_session_path %></a>
                  </li>
                <%end%>
               
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>


    <%if signed_in?%>
      <nav2 id="navbar" class="effect-shadow">
        <div class="slide-in-bar">
          <ul class="slide-in-bar__nav" style="background-color: #f5f5f5">
            <li><%= link_to "All Categories", user_posts_path(current_user.id) %></li>
            <li><%= link_to "Badminton", user_posts_path(current_user.id) %></li>
            <li><%= link_to "Running", user_posts_path(current_user.id) %></li>
            <li><%= link_to "Motorsport", user_posts_path(current_user.id) %></li>
            <li><%= link_to "Cycling", user_posts_path(current_user.id) %></li>
            <li><%= link_to "Yoga", user_posts_path(current_user.id) %></li>
            <li><%= link_to "Golf", user_posts_path(current_user.id) %></li>
          </ul>
        </div>
        <div class="hamburger-icon-wrapper"><span></span></div>
        
      <ul>
        <% if current_user %>
          <li class= link2 ><%= link_to "DEALS", user_posts_path(current_user.id) %></li>
          <li class= link2><%= link_to "WISHLISTS", wishlists_path %></li>
        <% end %>
      </ul>
    </nav2>
    <% end %>

        <!-- /.container-fluid -->
  </nav>


<%= yield %>


<footer>
    <div>
        <div class="footer" id="footer">
        
            <div class="container">
            
            <div class="row">
                <div class= "adjust-footer-container">
                    <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                        <h3> Company </h3>
                        <ul>
                            <li> <a href="#"> About </a> </li>
                            <li> <a href="#"> Terms & Privacy </a> </li>
                            <li> <a href="#"> Press </a> </li>
                            <li> <a href="#"> Blog </a> </li>
                        </ul>
                    </div>
                    <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                        <h3> Help </h3>
                        <ul>
                            <li> <a href="#"> Policies </a> </li>
                            <li> <a href="#"> Disaster Response </a> </li>
                            <li> <a href="#"> Terms & Conditions </a> </li>
                        </ul>
                    </div>
                    <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                        <h3> Discover </h3>
                        <ul>
                            <li> <a href="#"> Trust & Safety </a> </li>
                            <li> <a href="#"> Gift Cards </a> </li>
                            <li> <a href="#"> Mobile </a> </li>
                            <li> <a href="#"> Business Opportunity </a> </li>
                        </ul>
                    </div>
                    <div class="col-lg-2  col-md-2 col-sm-4 col-xs-6">
                        <h3> Products </h3>
                        <ul>
                            <li> <a href="#"> Product Policies </a> </li>
                            <li> <a href="#"> Terms </a> </li>
                            <li> <a href="#"> Safety </a> </li>
                            <li> <a href="#"> Posting Policies </a> </li>
                        </ul>
                    </div>
                    <div class="col-lg-3  col-md-3 col-sm-6 col-xs-12 ">
                        <h3> Media </h3>
                        <ul>
                            <li>
                                <div class="input-append newsletter-box text-center">
                                    <input type="text" class="full text-center" placeholder="Email ">
                                    <button class="btn  bg-gray" type="button"> Subscribe <i class="fa fa-long-arrow-right"> </i> </button>
                                </div>
                            </li>
                        </ul>
                        <ul class="social">
                            <li> <a href="#"> <i class=" fa fa-facebook">   </i> </a> </li>
                            <li> <a href="#"> <i class="fa fa-twitter">   </i> </a> </li>
                            <li> <a href="#"> <i class="fa fa-google-plus">   </i> </a> </li>
                            <li> <a href="#"> <i class="fa fa-pinterest">   </i> </a> </li>
                            <li> <a href="#"> <i class="fa fa-youtube">   </i> </a> </li>
                        </ul>
                    </div>
                </div>
                <!--/.row--> 
            </div>
        </div>
        <!--/.container--> 
    </div>
    <!--/.footer-->
</div>    
            <div class="footer-bottom">
                <div class="container">
                    <p class="pull-left"> Copyright © Footer E-commerce Plugin 2016. All rights reserved. </p>
                    <div class="pull-right">
                        <ul class="nav nav-pills payments">
                          <li><i class="fa fa-cc-visa"></i></li>
                            <li><i class="fa fa-cc-mastercard"></i></li>
                            <li><i class="fa fa-cc-amex"></i></li>
                            <li><i class="fa fa-cc-paypal"></i></li>
                        </ul> 
                    </div>
                </div>
            </div>
      
</footer>
</body>
</html>